[platformio]
default_envs = T5-ePaper-S3

[env]
platform = espressif32@6.12.0
framework = arduino

upload_speed = 115200
monitor_speed = 115200

lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#esp32s3
    https://github.com/lewisxhe/SensorLib.git
    bblanchon/ArduinoJson@^7.4.2

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_filters =
    default
    esp32_exception_decoder

extra_scripts =
    pre:scripts/patch_lilygo_epd.py

custom_lilygo_epd_frame_count = 9

[env:T5-ePaper-S3]
extends = env

board = lilygo_t5_epaper_s3_n16r8

board_build.mcu = esp32s3

board_build.flash_mode = dio
board_build.f_flash = 80000000L

board_build.arduino.memory_type = qio_opi

board_upload.flash_size = 16MB

board_build.partitions = default_16MB.csv

build_flags =
    ${env.build_flags}
    -DCONFIG_SPIRAM_MODE_OCT=1
    -DCONFIG_SPIRAM_TYPE_ESPPSRAM64=1
    -DLILYGO_T5_EPD47_S3
    -DMAP_DOWNLOAD_BASE_URL=\"https://randalrenye.github.io/brvario-epaper/regions\"
    -DFLIGHT_SITE_CATALOG_URL=\"https://randalrenye.github.io/brvario-epaper/weather/catalog.json\"
