#pragma once

#include <stddef.h>
#include <stdint.h>

#include "epd_driver.h"

enum class TouchAction : uint8_t {
  None,
  Back,
  OpenMenu,
  NextPage,
  ToggleAltimeter,
  ToggleAudio,
  ToggleTracklog,
  TracklogBleCancel,
  Home,
  PowerRequest,
  PowerHold,
  PowerOff,
  PowerConfirmYes,
  PowerConfirmNo,
  OpenSettings,
  CenterGauge,
  OpenAudioEditor,
  OpenWifiSettings,
  OpenFirmwareUpdate,
  OpenWeatherStation,
  OpenPilotProfile,
  OpenThermalCycleBeta,
  OpenDashboardLayout,
  OpenThermalAssistSettings,
  OpenDeviceInfo,
  OpenSystemStatus,
  OpenManual,
  OpenManualLogic,
  OpenManualUser,
  OpenStorageManager,
  OpenAdvancedSystem,
  OpenMapDownload,
  StorageRefresh,
  StorageClearMaps,
  AdvancedRecoverDisplay,
  AdvancedMoveIgcToSd,
  AdvancedClearWifi,
  AdvancedResetSettings,
  AdvancedClearWeatherCache,
  AdvancedFormatSystem,
  AdvancedConfirmYes,
  AdvancedConfirmNo,
  MapDownloadSelect0,
  MapDownloadSelect1,
  MapDownloadSelect2,
  MapDownloadSelect3,
  MapDownloadSelect4,
  MapDownloadSelect5,
  MapDownloadStart,
  MapDownloadCancel,
  MapDownloadBack,
  MapZoomIn,
  MapZoomOut,
  MapPanUp,
  MapPanDown,
  MapPanLeft,
  MapPanRight,
  DashboardLayoutMove,
  DashboardLayoutSave,
  DashboardLayoutReset,
  AudioSave,
  AudioReset,
  AudioResponseDown,
  AudioResponseUp,
  AudioPitchDown,
  AudioPitchUp,
  AudioVolumeSet,
  AudioVoiceToggle,
  ThermalModePilot,
  ThermalModeThermal,
  ThermalInfo,
  ThermalInfoUp,
  ThermalInfoDown,
  ThermalCycleInfo,
  ThermalCycleInfoUp,
  ThermalCycleInfoDown,
  WeatherPrevDay,
  WeatherNextDay,
  WeatherInfo,
  WeatherInfoUp,
  WeatherInfoDown,
  OpenWeatherLocation,
  WeatherLocationAction,
  ManualPageUp,
  ManualPageDown,
  ManualTab0,
  ManualTab1,
  ManualTab2,
  ManualTab3,
  ManualTab4,
};

struct TouchZone {
  Rect_t bounds;
  TouchAction action;
  bool enabled;
};

inline bool pointInRect(const Rect_t& rect, int32_t x, int32_t y) {
  return x >= rect.x && x < rect.x + rect.width && y >= rect.y && y < rect.y + rect.height;
}
