#!/usr/bin/env python3
"""Generate the compact firmware catalog for Brazilian regional maps."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


MACROS = [
    ("norte", "NORTE"),
    ("nordeste", "NORDESTE"),
    ("centro_oeste", "CENTRO-OESTE"),
    ("sudeste", "SUDESTE"),
    ("sul", "SUL"),
]

STATES = [
    ("AC", "Acre", 0),
    ("AP", "Amapa", 0),
    ("PA", "Para", 0),
    ("RO", "Rondonia", 0),
    ("RR", "Roraima", 0),
    ("TO", "Tocantins", 0),
    ("AL", "Alagoas", 1),
    ("BA", "Bahia", 1),
    ("CE", "Ceara", 1),
    ("MA", "Maranhao", 1),
    ("PB", "Paraiba", 1),
    ("PE", "Pernambuco", 1),
    ("PI", "Piaui", 1),
    ("RN", "Rio Grande do Norte", 1),
    ("SE", "Sergipe", 1),
    ("DF", "Distrito Federal", 2),
    ("GO", "Goias", 2),
    ("MT", "Mato Grosso", 2),
    ("MS", "Mato Grosso do Sul", 2),
    ("ES", "Espirito Santo", 3),
    ("MG", "Minas Gerais", 3),
    ("RJ", "Rio de Janeiro", 3),
    ("SP", "Sao Paulo", 3),
    ("PR", "Parana", 4),
    ("RS", "Rio Grande do Sul", 4),
    ("SC", "Santa Catarina", 4),
]


def e7(value: float) -> int:
    return int(round(value * 10_000_000))


def package_number(region_id: str) -> int:
    match = re.search(r"_(\d+)$", region_id)
    if not match:
        raise ValueError(f"Invalid region id: {region_id}")
    return int(match.group(1))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate BrazilMapCatalog.h")
    parser.add_argument("--plan", type=Path, default=Path("build/maps-brasil/catalog.plan.json"))
    parser.add_argument("--output", type=Path, default=Path("src/network/BrazilMapCatalog.h"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    state_index = {uf: index for index, (uf, _, _) in enumerate(STATES)}

    packages = []
    for entry in plan:
        uf = entry["state"]
        if uf not in state_index:
            continue
        packages.append(
            {
                "state": uf,
                "state_index": state_index[uf],
                "number": package_number(entry["id"]),
                "lat_min": e7(entry["latMin"]),
                "lat_max": e7(entry["latMax"]),
                "lon_min": e7(entry["lonMin"]),
                "lon_max": e7(entry["lonMax"]),
            }
        )
    packages.sort(key=lambda item: (item["state_index"], item["number"]))

    first_by_state = {uf: 0 for uf, _, _ in STATES}
    count_by_state = {uf: 0 for uf, _, _ in STATES}
    for index, package in enumerate(packages):
        uf = package["state"]
        if count_by_state[uf] == 0:
            first_by_state[uf] = index
        count_by_state[uf] += 1

    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "// Generated by scripts/make_brazil_catalog_header.py.",
        "// Contains only compact metadata used for offline map navigation.",
        "",
        "struct BrazilMacroRegionInfo {",
        "  const char* id;",
        "  const char* name;",
        "};",
        "",
        "struct BrazilStateInfo {",
        "  const char* uf;",
        "  const char* name;",
        "  uint8_t macroIndex;",
        "  uint16_t firstPackage;",
        "  uint16_t packageCount;",
        "};",
        "",
        "struct BrazilMapPackageInfo {",
        "  uint8_t stateIndex;",
        "  uint16_t number;",
        "  int32_t latMinE7;",
        "  int32_t latMaxE7;",
        "  int32_t lonMinE7;",
        "  int32_t lonMaxE7;",
        "};",
        "",
        f"static constexpr uint8_t kBrazilMacroRegionCount = {len(MACROS)};",
        "static constexpr BrazilMacroRegionInfo kBrazilMacroRegions[] = {",
    ]
    for macro_id, name in MACROS:
        lines.append(f'    {{"{macro_id}", "{name}"}},')
    lines.extend([
        "};",
        "",
        f"static constexpr uint8_t kBrazilStateCount = {len(STATES)};",
        "static constexpr BrazilStateInfo kBrazilStates[] = {",
    ])
    for uf, name, macro_index in STATES:
        lines.append(
            f'    {{"{uf}", "{name}", {macro_index}, {first_by_state[uf]}, {count_by_state[uf]}}},'
        )
    lines.extend([
        "};",
        "",
        f"static constexpr uint16_t kBrazilMapPackageCount = {len(packages)};",
        "static constexpr BrazilMapPackageInfo kBrazilMapPackages[] = {",
    ])
    for package in packages:
        lines.append(
            "    "
            f"{{{package['state_index']}, {package['number']}, "
            f"{package['lat_min']}, {package['lat_max']}, {package['lon_min']}, {package['lon_max']}}},"
        )
    lines.extend([
        "};",
        "",
    ])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.output} with {len(packages)} packages")


if __name__ == "__main__":
    main()
